import { useState } from "react";
import { Download } from "lucide-react";
import { Button, Card, Field, Input } from "./ui";
import type { OperationsReport as Report, Product } from "@/lib/types";
import { formatZar } from "@/lib/money";

function downloadCsv(report: Report) {
  const cells = [["Date (South Africa)", "Paid orders", "Sales (R)"], ...report.daily.map(d => [d.day, d.orders, (d.sales / 100).toFixed(2)])];
  const csv = cells.map(row => row.map(value => `"${String(value).replaceAll('"','""')}"`).join(",")).join("\r\n");
  const url = URL.createObjectURL(new Blob([csv], {type:"text/csv;charset=utf-8"}));
  const link = document.createElement("a"); link.href = url; link.download = "plugos-sales-30-days.csv"; link.click(); URL.revokeObjectURL(url);
}
export function OperationsReport({ report, products }: { report: Report; products: Product[] }) {
  const [query, setQuery] = useState("");
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-3xl">Sales and operations</h2><p className="mt-1 text-sm text-muted">Last 30 days · South African trading dates · paid sales</p></div><Button variant="secondary" onClick={() => downloadCsv(report)}><Download className="h-4 w-4" /> Export sales</Button></div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><h3 className="font-display text-2xl">Daily sales</h3><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-line text-muted"><th className="py-2">Day</th><th className="text-right">Orders</th><th className="text-right">Sales</th></tr></thead><tbody>{report.daily.map(d => <tr key={d.day} className="border-b border-line"><td className="py-3">{d.day}</td><td className="text-right font-mono">{d.orders}</td><td className="text-right font-mono">{formatZar(d.sales)}</td></tr>)}</tbody></table>{!report.daily.length ? <p className="py-4 text-sm text-muted">Paid sales will appear here after the first payment.</p> : null}</div></Card>
      <Card><h3 className="font-display text-2xl">Best sellers</h3><div className="mt-4 space-y-3">{report.topProducts.map(p => <div key={p.name} className="flex items-center justify-between gap-4 border-b border-line pb-3"><div className="min-w-0"><strong className="text-sm">{p.name}</strong><p className="text-xs text-muted">{p.quantity} sold</p></div><span className="shrink-0 font-mono text-sm">{formatZar(p.sales)}</span></div>)}{!report.topProducts.length ? <p className="text-sm text-muted">No sales yet.</p> : null}</div></Card>
    </div>
    <Card><h3 className="font-display text-2xl">Cash-up history</h3><p className="mt-1 text-sm text-muted">Latest 30 shifts. Variance compares the physical count with the opening float plus payments.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{report.shifts.map(s => <article key={s.id} className="rounded-lg bg-warm p-4 text-sm"><strong>{s.opened_by}</strong><p className="mt-1 text-xs text-muted">{new Date(s.opened_at).toLocaleString("en-ZA",{timeZone:"Africa/Johannesburg"})} · {s.status === "OPEN" ? "Open" : "Closed"}</p><dl className="mt-3 space-y-1"><div className="flex justify-between gap-2"><dt>Opening float</dt><dd className="font-mono">{formatZar(s.opening_float_cents)}</dd></div>{s.expected_cents !== null && s.counted_cents !== null ? <><div className="flex justify-between gap-2"><dt>Expected</dt><dd className="font-mono">{formatZar(s.expected_cents)}</dd></div><div className="flex justify-between gap-2"><dt>Counted</dt><dd className="font-mono">{formatZar(s.counted_cents)}</dd></div><div className="flex justify-between gap-2 font-semibold"><dt>Variance</dt><dd className="font-mono">{formatZar(s.counted_cents-s.expected_cents)}</dd></div></> : null}</dl></article>)}</div>{!report.shifts.length ? <p className="mt-4 text-sm text-muted">No shifts opened yet.</p> : null}</Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><h3 className="font-display text-2xl">Stock on hand</h3><div className="mt-3"><Field label="Search stock"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a menu item" /></Field></div><div className="mt-3 space-y-2">{products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><div key={p.id} className="flex items-center justify-between gap-3 rounded-lg bg-warm p-3 text-sm"><span>{p.name}</span><strong className={`font-mono ${p.stock<=5 ? "text-alert":"text-ink"}`}>{p.stock}</strong></div>)}</div></Card>
    <Card><h3 className="font-display text-2xl">Stock activity</h3><p className="mt-1 text-sm text-muted">Latest 100 receipts, counts and waste records.</p><div className="mt-4 space-y-3">{report.inventory.map(i=><article key={i.id} className="border-b border-line pb-3 text-sm"><strong>{i.name}</strong><p>{i.kind === "RECEIPT" ? "Received" : i.kind === "COUNT" ? "Counted" : "Waste"} · {i.qty}</p>{i.reason ? <p className="text-muted">{i.reason}</p> : null}<p className="text-xs text-muted">{new Date(i.created_at).toLocaleString("en-ZA",{timeZone:"Africa/Johannesburg"})}</p></article>)}{!report.inventory.length ? <p className="text-sm text-muted">No stock activity yet.</p> : null}</div></Card></div>
  </div>;
}
