/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StationRouteImport } from './routes/station'
import { Route as StationIndexRouteImport } from './routes/station.index'
import { Route as StationCashierRouteImport } from './routes/station.cashier'
import { Route as StationKitchenRouteImport } from './routes/station.kitchen'
import { Route as StationManagerRouteImport } from './routes/station.manager'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StationRoute = StationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIndexRoute = StationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StationRoute,
} as any)
const StationCashierRoute = StationCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => StationRoute,
} as any)
const StationKitchenRoute = StationKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => StationRoute,
} as any)
const StationManagerRoute = StationManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => StationRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/station': typeof StationRouteWithChildren
  '/station/cashier': typeof StationCashierRoute
  '/station/kitchen': typeof StationKitchenRoute
  '/station/manager': typeof StationManagerRoute
  '/station/': typeof StationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/station/cashier': typeof StationCashierRoute
  '/station/kitchen': typeof StationKitchenRoute
  '/station/manager': typeof StationManagerRoute
  '/station': typeof StationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/station': typeof StationRouteWithChildren
  '/station/cashier': typeof StationCashierRoute
  '/station/kitchen': typeof StationKitchenRoute
  '/station/manager': typeof StationManagerRoute
  '/station/': typeof StationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/owner'
    | '/setup'
    | '/station'
    | '/station/cashier'
    | '/station/kitchen'
    | '/station/manager'
    | '/station/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/owner'
    | '/setup'
    | '/station/cashier'
    | '/station/kitchen'
    | '/station/manager'
    | '/station'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/owner'
    | '/setup'
    | '/station'
    | '/station/cashier'
    | '/station/kitchen'
    | '/station/manager'
    | '/station/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  SetupRoute: typeof SetupRoute
  StationRoute: typeof StationRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station': {
      id: '/station'
      path: '/station'
      fullPath: '/station'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/': {
      id: '/station/'
      path: '/'
      fullPath: '/station/'
      preLoaderRoute: typeof StationIndexRouteImport
      parentRoute: typeof StationRoute
    }
    '/station/cashier': {
      id: '/station/cashier'
      path: '/cashier'
      fullPath: '/station/cashier'
      preLoaderRoute: typeof StationCashierRouteImport
      parentRoute: typeof StationRoute
    }
    '/station/kitchen': {
      id: '/station/kitchen'
      path: '/kitchen'
      fullPath: '/station/kitchen'
      preLoaderRoute: typeof StationKitchenRouteImport
      parentRoute: typeof StationRoute
    }
    '/station/manager': {
      id: '/station/manager'
      path: '/manager'
      fullPath: '/station/manager'
      preLoaderRoute: typeof StationManagerRouteImport
      parentRoute: typeof StationRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StationRouteChildren {
  StationCashierRoute: typeof StationCashierRoute
  StationKitchenRoute: typeof StationKitchenRoute
  StationManagerRoute: typeof StationManagerRoute
  StationIndexRoute: typeof StationIndexRoute
}

const StationRouteChildren: StationRouteChildren = {
  StationCashierRoute: StationCashierRoute,
  StationKitchenRoute: StationKitchenRoute,
  StationManagerRoute: StationManagerRoute,
  StationIndexRoute: StationIndexRoute,
}

const StationRouteWithChildren =
  StationRoute._addFileChildren(StationRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  SetupRoute: SetupRoute,
  StationRoute: StationRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
